### PR TITLE
Fix, Solution for issue #7, Extension method for path fixup

### PR DESCRIPTION
**Pull request by Teun**
Three fixes, really. Note that I've only tested with Mvc 2, so you might want to test with Mvc 3 before merging.

### CODE REVIEW

**Comment by janjongboom** [comment]
I merged c937736.

**Comment by janjongboom** [comment]
@Teun Easy fix I just came up with: in the constructor write something like `<!-- Moth.Script.Start endoffile -->` and in the destructor `<!-- Moth.Script.End -->`. Then in the `MothAction` we just read those parts. Might be easier. Need to handle multiple thingy's, inline etc. etc. but that's not too hard. Other ideas?

**Comment by Teun** [comment]
Yes, seems like a fine solution. Will work for all view engines, but less cool. Should we consider nested blocks? Html.BeginScript will not (as far as I can see) ever be used in a nested way, but maybe in other places?

**Comment by janjongboom** [comment]
Yeah, it's quite lame and it might be a bit error prone. For now we don't need nested blocks but I think you want to offer this in a generic interface in the future. Can work that out later on. We can be ready for the future however by adding a GUID to the start / end tags. Then regex'ing the part is easy peasy with something like `<\!-- Moth\.Script\.Start ([\w-]{32}) (endoffile|inplace) -->.+<\!-- Moth\.Script\.End \1-->`. Won't get messed up this way if doing nesting.

**Comment by Teun** [comment]
Yes, much better. That would also prevent things screwing up when someone adds the magic comment to the HTML.

**Comment by janjongboom** [comment]
I'll close this one, will commit something similar as the pluggable path resolver. Other fixes are cherry picked or live on in #10.

**Pull request closed without merging**
