### PR TITLE
Implementation of the idea you suggested in Issue 7

### PR DESCRIPTION
**Pull request by Teun**
Moved inline script logic to the script executor.

### CODE REVIEW

**Comment by janjongboom** [comment]
Hi @teun, it seems you aren't checking whether the GUIDs match between the start and end tag. Also: is it necessary to have two seperate regex'es for this, can't we combine them into one?

**Comment by Teun** [comment]
Yeah, good point. I forgot to fix that. It will work fine now, though as it only breaks on nested blocks and I currently see no real world need for that. But if you wait I'll add that too.

**Comment by Teun** [comment]
Works as you suggested now. It will still break on nested usage of `Html.BeginScript` though. The expression will ignore occurrences of the start marker within other matches. The javascript minification will then fail on the <% Moth.BeginScript.

I have been thinking about cases where you would want to wrap these calls and I just couldn't come up with one. What we might do is check for nested occurences and give a more helpful error message.

**Comment by janjongboom** [comment]
Reviewed this, it looks good and it even works :-)

**Pull request merged**
